[phases.setup]
nixPkgs = ["nginx", "php82", "php82Extensions.pdo", "php82Extensions.pdo_pgsql", "php82Extensions.pgsql", "php82Extensions.opcache", "gettext"]

[phases.build]

[start]
cmd = "sh /app/start.sh"
