# See https://docs.wasmer.io/deployment/reference/wasmer-toml
[package]
name = "mongkol7/app"
version = "0.1.0"
description = "PHP CRUD application"

# This section fixes the 404 error by telling the server
# to use the "public" directory as the web root.
[package.annotations.http]
root = "public"

# This section fixes the 500 database error.
# It is highly recommended to use `wasmer secret` for sensitive values.
# See: https://docs.wasmer.io/deployment/reference/secrets
[package.env]
DB_HOST = "aws-1-ap-southeast-1.pooler.supabase.com"
DB_PORT = "5432"
DB_NAME = "postgres"
DB_USER = "postgres.ewhjmxkowruxlvqkzlyv"
# IMPORTANT: If you reset your password, you must put the new one here.
DB_PASS = "etec18104123"
